name: CI Back-end Compile and Test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapi/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'
  workflow_call:

jobs:

  main:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-backend.yml

  build:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Maven Compile
        working-directory: sgcmapi/
        run: mvn compile
      - name: Maven Test
        working-directory: sgcmapi/
        run: mvn test
