name: CI Back-end Branches

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'sgcmapi/**'

permissions:
  contents: write

jobs:

  test:
    name: CI Workflow Test
    uses: ./.github/workflows/ci-backend-test.yml
  
  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
